In [1]:
import torch
import numpy as np

In [2]:
torch.Tensor(5, 4)

tensor([[ 7.5537e-37,  0.0000e+00,  6.0256e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  1.3733e-14,  9.5680e+20],
        [ 7.2065e+31,  2.6301e+20,  1.4601e-19,  6.4069e+02],
        [ 4.3066e+21,  1.1824e+22,  4.3066e+21,  6.3828e+28],
        [ 3.8016e-39,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [3]:
torch.rand(5, 4)

tensor([[ 0.7258,  0.8116,  0.8203,  0.3740],
        [ 0.3941,  0.4025,  0.8346,  0.8967],
        [ 0.0736,  0.3973,  0.9237,  0.1234],
        [ 0.4332,  0.6658,  0.2405,  0.1569],
        [ 0.7188,  0.7333,  0.5685,  0.2664]])

In [4]:
a = torch.rand(5, 5)
a.size()

torch.Size([5, 5])

In [5]:
np.ones((5, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [6]:
a = torch.rand(5, 5)
b = a.numpy()
print(b)

[[ 0.6021235   0.46670824  0.22745287  0.60059112  0.34200472]
 [ 0.06085724  0.6561175   0.0411126   0.63788861  0.34110409]
 [ 0.65715438  0.13704908  0.65180141  0.40988356  0.10478371]
 [ 0.75503784  0.45156294  0.78489494  0.3308875   0.80783957]
 [ 0.32358497  0.15543169  0.0373286   0.24785948  0.44691348]]


In [7]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(a)

[[3 4]
 [3 6]]


In [8]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3
print(c*x)

tensor([[ 0.1459,  0.0795,  2.2001,  1.0459],
        [ 0.0826,  1.8146,  2.3179,  1.2194],
        [ 2.0288,  0.6493,  1.6268,  0.7882],
        [ 1.3682,  0.2291,  1.7882,  1.5958],
        [ 1.0465,  0.2106,  1.7432,  1.4942]])


In [9]:
print(x+y)

tensor([[ 0.1040,  0.4478,  1.3780,  0.8503],
        [ 0.1682,  1.1784,  1.1599,  0.7506],
        [ 0.9668,  0.9495,  1.0766,  1.0679],
        [ 0.5855,  0.2279,  0.9229,  1.0983],
        [ 1.2115,  0.8331,  0.9593,  0.6578]])


In [10]:
print(x.add(y))

tensor([[ 0.1040,  0.4478,  1.3780,  0.8503],
        [ 0.1682,  1.1784,  1.1599,  0.7506],
        [ 0.9668,  0.9495,  1.0766,  1.0679],
        [ 0.5855,  0.2279,  0.9229,  1.0983],
        [ 1.2115,  0.8331,  0.9593,  0.6578]])


In [11]:
torch.cuda.is_available()

False

In [12]:
from torch.autograd import Variable

In [13]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [14]:
z.backward()

In [15]:
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([ 2.])
dz/dy: tensor([ 1.])
